version: '3'

services:
  server:
    container_name: devcamp-project-server-local
    image: devcamp-project-server-local:latest
    restart: always
    depends_on:
      - postgres
    networks:
      - devcamp-project
    environment:
      - ENV=local
      - TZ=Asia/Seoul
  proxy:
    container_name: devcamp-project-nginx-local
    image: devcamp-project-nginx-local:latest
    restart: always
    networks:
      - devcamp-project
    ports:
      - 4000:80
    volumes:
      - ./proxy/nginx-local.conf:/etc/nginx/nginx.conf
  postgres:
    image: postgres:latest
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: love1221!@
      POSTGRES_DB: devcamp-project
    ports:
      - '5432:5432'
    volumes:
      - $PWD/volumes/postgres_data:/var/lib/postgresql/data
networks:
  devcamp-project:
    external: true
